In [38]:
print('In the name of Allah')

In the name of Allah

In [39]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [40]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [41]:
df.shape

(569, 33)

In [42]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [43]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

# Train, test and split

In [44]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size = 0.2)

In [45]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [46]:
X_train

array([[ 0.33890531,  0.6879289 ,  0.29804307, ...,  0.14168369,
         0.44853689,  0.73325453],
       [-1.09587918, -0.41503838, -1.0832971 , ..., -0.88422287,
         0.2529477 ,  0.20058858],
       [ 1.40514712,  1.23037183,  1.49874645, ...,  2.08607205,
         2.88525228,  1.06541955],
       ...,
       [-0.17311582,  1.99883265, -0.23446765, ..., -0.8526093 ,
        -0.3354498 , -0.74782997],
       [-0.30534106, -1.16089741, -0.30843883, ..., -0.84202028,
        -0.76248621,  0.90698558],
       [-0.65419062, -0.40825785, -0.64314817, ..., -0.18979846,
        -0.68751035, -0.36758843]])

In [47]:
y_train

184    M
222    B
42     M
234    B
465    B
      ..
113    B
165    B
377    B
336    B
530    B
Name: diagnosis, Length: 455, dtype: object

# Label Encoding

In [48]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [49]:
y_train

array([1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0])

# Numpy arrays to PyTorch tensors

In [50]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [51]:
type(X_train_tensor)

torch.Tensor

In [52]:
y_train_tensor.shape

torch.Size([455])

# Defining the model

In [53]:
X_train.shape[1]

30

In [90]:
class MySimpleNN() :

  def __init__( self, X ) :
    self.weights = torch.rand( X.shape[1], 1, dtype = torch.float64, requires_grad = True )
    self.bias = torch.zeros( 1, dtype = torch.float64, requires_grad = True )

  def forward( self, X ) :
    z = torch.matmul( X, self.weights ) + self.bias
    y_pred = torch.sigmoid(z)

    return y_pred


  def loss_function( self, y_pred, y ) :
    # clamp

    epsilon = 1e-7

    y_pred = torch.clamp( y_pred, epsilon, 1 - epsilon )
    loss = -( y_train_tensor * torch.log( y_pred ) + ( 1 - y_train_tensor ) * torch.log(1 - y_pred) ).mean()

    return loss

In [91]:
torch.rand(30, 1)

tensor([[0.5399],
        [0.5403],
        [0.7541],
        [0.3686],
        [0.8287],
        [0.7508],
        [0.3125],
        [0.3950],
        [0.0200],
        [0.2912],
        [0.3910],
        [0.4228],
        [0.7063],
        [0.4334],
        [0.6778],
        [0.1255],
        [0.0815],
        [0.1297],
        [0.4498],
        [0.7074],
        [0.9394],
        [0.1949],
        [0.1670],
        [0.8081],
        [0.2813],
        [0.4928],
        [0.1318],
        [0.4626],
        [0.5543],
        [0.6894]])

In [92]:
model = MySimpleNN( X_train_tensor )

In [93]:
model.weights

tensor([[0.4746],
        [0.5792],
        [0.9180],
        [0.1376],
        [0.2309],
        [0.8511],
        [0.5453],
        [0.8659],
        [0.4571],
        [0.1396],
        [0.7243],
        [0.0027],
        [0.0197],
        [0.7850],
        [0.3587],
        [0.0933],
        [0.6402],
        [0.3734],
        [0.7689],
        [0.4402],
        [0.4572],
        [0.6612],
        [0.0263],
        [0.1798],
        [0.8180],
        [0.7685],
        [0.5574],
        [0.1246],
        [0.5047],
        [0.6570]], dtype=torch.float64, requires_grad=True)

In [94]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

## Parameters

In [95]:
learning_rate = 0.1
epochs = 25

# Training Pipeline

In [96]:
# Create Model

model = MySimpleNN( X_train_tensor )

# define loop

for epoch in range(epochs) :

  # forward pass

  y_pred = model.forward(X_train_tensor)

  # Loss calculate

  loss = model.loss_function( y_pred, y_train_tensor )

  # backward pass

  loss.backward()

  # parameter update

  with torch.no_grad() :
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradient
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch

  print(f'{epoch + 1}, Loss = {loss.item()}')

1, Loss = 3.363807589972496
2, Loss = 3.2369664867173684
3, Loss = 3.104542910955865
4, Loss = 2.9680498427966646
5, Loss = 2.826359095169712
6, Loss = 2.6754170187061734
7, Loss = 2.513193453129375
8, Loss = 2.349513872131325
9, Loss = 2.1814299486989426
10, Loss = 2.014976410013601
11, Loss = 1.8555755453570129
12, Loss = 1.7046225285472019
13, Loss = 1.5630613700858715
14, Loss = 1.4292124252804985
15, Loss = 1.3050232798812091
16, Loss = 1.1929621203936898
17, Loss = 1.0976455801460747
18, Loss = 1.0194373942502781
19, Loss = 0.9577847929383252
20, Loss = 0.9110990845041892
21, Loss = 0.8768882910284387
22, Loss = 0.8522351551536383
23, Loss = 0.8343881431353394
24, Loss = 0.8211378210297097
25, Loss = 0.8109005538410059

## Model Evaluation

In [97]:
y_pred = model.forward( X_test_tensor )

In [98]:
y_pred

tensor([[0.4954],
        [0.1146],
        [0.6272],
        [0.8597],
        [0.5464],
        [0.1299],
        [0.1912],
        [0.6734],
        [0.8143],
        [0.3614],
        [0.2878],
        [0.5624],
        [0.1725],
        [0.3369],
        [0.3823],
        [0.4044],
        [0.3475],
        [0.6171],
        [0.9925],
        [0.3627],
        [0.4904],
        [0.3311],
        [0.8397],
        [0.6346],
        [0.1672],
        [0.3460],
        [0.2736],
        [0.2250],
        [0.3994],
        [0.8090],
        [0.6509],
        [0.3847],
        [0.1868],
        [0.4270],
        [0.6749],
        [0.4277],
        [0.4256],
        [0.4076],
        [0.3698],
        [0.5619],
        [0.2545],
        [0.1607],
        [0.4457],
        [0.3208],
        [0.5232],
        [0.6326],
        [0.4845],
        [0.4416],
        [0.4120],
        [0.1659],
        [0.3112],
        [0.2751],
        [0.3985],
        [0.8265],
        [0.3502],
        [0.6330],
        [0.6124],
        [0.8486],
        [0.4740],
        [0.2522],
        [0.4703],
        [0.7369],
        [0.2510],
        [0.5774],
        [0.2683],
        [0.3056],
        [0.1893],
        [0.3178],
        [0.4780],
        [0.9492],
        [0.2251],
        [0.2953],
        [0.7918],
        [0.3982],
        [0.0967],
        [0.3941],
        [0.7103],
        [0.1693],
        [0.3706],
        [0.3296],
        [0.6247],
        [0.2801],
        [0.4021],
        [0.3618],
        [0.2834],
        [0.4075],
        [0.4062],
        [0.2884],
        [0.1685],
        [0.4838],
        [0.4586],
        [0.5096],
        [0.0468],
        [0.3346],
        [0.9047],
        [0.5650],
        [0.4385],
        [0.6044],
        [0.7120],
        [0.3877],
        [0.3672],
        [0.9415],
        [0.1198],
        [0.1999],
        [0.5018],
        [0.7526],
        [0.2660],
        [0.6916],
        [0.1701],
        [0.2728],
        [0.3223],
        [0.2174],
        [0.6854],
        [0.3148]], dtype=torch.float64, grad_fn=<SigmoidBackward0>)

In [101]:
( y_pred > 0.9 ).float()

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])

In [100]:
y_pred = ( y_pred > 0.9 ).float()

In [107]:
accuracy = ( y_pred == y_test_tensor ).float().mean()

In [109]:
print(f'Accuracy : {accuracy.item()}')

Accuracy : 0.6223453283309937

In [110]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6223453283309937