In [346]:
print('In the name of Allah')

In the name of Allah

# Import Libraries

In [347]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [348]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [349]:
df.shape

(569, 33)

In [350]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [351]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

# Train test split

In [352]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [353]:
df['diagnosis'].unique()

array(['M', 'B'], dtype=object)

In [354]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [355]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [356]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [357]:
len(df.columns)

31

In [358]:
X_train

array([[-0.63457787, -0.10915808, -0.56314573, ...,  0.63642194,
         2.99687468,  3.19256405],
       [ 1.44683227, -0.78844806,  1.42941842, ...,  0.99553908,
        -0.73674895, -1.17529051],
       [-0.65723268, -0.24698503, -0.68384478, ..., -0.6539124 ,
        -1.48572867, -0.80197922],
       ...,
       [-0.33723357, -1.48250522, -0.40001665, ..., -0.93281117,
        -0.95258396, -0.80197922],
       [ 1.19762943,  0.35354669,  1.20285024, ...,  0.58045563,
         0.27960847, -0.26899864],
       [-0.58926827, -0.85982273, -0.60351606, ..., -0.58053435,
         0.77087474, -0.23470347]])

In [359]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0])

In [360]:
X_train

array([[-0.63457787, -0.10915808, -0.56314573, ...,  0.63642194,
         2.99687468,  3.19256405],
       [ 1.44683227, -0.78844806,  1.42941842, ...,  0.99553908,
        -0.73674895, -1.17529051],
       [-0.65723268, -0.24698503, -0.68384478, ..., -0.6539124 ,
        -1.48572867, -0.80197922],
       ...,
       [-0.33723357, -1.48250522, -0.40001665, ..., -0.93281117,
        -0.95258396, -0.80197922],
       [ 1.19762943,  0.35354669,  1.20285024, ...,  0.58045563,
         0.27960847, -0.26899864],
       [-0.58926827, -0.85982273, -0.60351606, ..., -0.58053435,
         0.77087474, -0.23470347]])

In [361]:
type(y_train)

numpy.ndarray

In [362]:
type(y_test)

numpy.ndarray

# Numpy Array to tensors

In [363]:
#numpy to tensor
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)

#change dtype
X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)

#numpy to tensor
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

y_train_tensor = torch.tensor(y_train_tensor,dtype= torch.float32)
y_test_tensor = torch.tensor(y_test_tensor, dtype=torch.float32)

# y_test_tensor = torch.from_numpy(y_test)

/tmp/ipykernel_528/3826779354.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
/tmp/ipykernel_528/3826779354.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)
/tmp/ipykernel_528/3826779354.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_train_tensor = torch.tensor(y_train_tensor,dtype= torch.float32)
/tmp/ipykernel_528/3826779354.py:14: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_tensor = torch.tensor(y_test_tensor, dtype=torch.float32)

In [364]:
type(X_train_tensor)

torch.Tensor

# Dataset and DataLoader

In [365]:
from torch.utils.data import Dataset, DataLoader

In [366]:
class CustomDataset( Dataset ) :
  def __init__( self, features, labels ) :
    self.features = features
    self.labels = labels

  def __len__(self):
        return self.features.shape[0]

  def __getitem__(self, idx):
      return self.features[idx], self.labels[idx]

In [367]:
train_dataset = CustomDataset( X_train_tensor, y_train_tensor )
test_dataset = CustomDataset( X_test_tensor, y_test_tensor )

In [368]:
len(train_dataset)

455

In [369]:
train_dataset[2]

(tensor([-0.6572, -0.2470, -0.6838, -0.6243,  0.2396, -0.8631, -0.7702, -0.3436,
         -0.7018,  0.0238,  0.8362,  1.5802,  0.6126,  0.1799, -0.4958, -0.8544,
         -0.6236,  0.3966, -0.6106, -0.3811, -0.5948, -0.3571, -0.6508, -0.5714,
         -0.8156, -1.1180, -1.0219, -0.6539, -1.4857, -0.8020]),
 tensor(1.))

# DataLoader

In [370]:
train_loader = DataLoader( train_dataset, batch_size = 32, shuffle = True )
test_loader = DataLoader( test_dataset, batch_size = 32, shuffle = True )

## Defining the Model

In [371]:
X_train.shape[1]

30

In [372]:
import torch.nn as nn

In [373]:
class MySimpleNN(nn.Module):

  def __init__(self,num_features):
    super().__init__()

    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [374]:
torch.rand(30,1)

tensor([[0.1402],
        [0.1451],
        [0.4810],
        [0.2941],
        [0.8309],
        [0.7502],
        [0.2219],
        [0.1525],
        [0.8464],
        [0.6127],
        [0.6681],
        [0.3815],
        [0.1350],
        [0.1374],
        [0.3239],
        [0.2747],
        [0.3768],
        [0.7585],
        [0.3426],
        [0.3440],
        [0.0123],
        [0.3475],
        [0.0205],
        [0.9495],
        [0.7601],
        [0.5804],
        [0.7870],
        [0.4431],
        [0.8928],
        [0.7178]])

# Parameters

In [375]:
X_train_tensor.shape[1]

30

In [376]:
learning_rate = 0.1
epochs = 25

In [377]:
loss_function = nn.BCELoss()

In [378]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [379]:
model = MySimpleNN(X_train_tensor.shape[1])

In [380]:
model.parameters()

In [381]:
X_test_tensor.dtype

torch.float32

In [382]:
model.linear.weight.dtype

torch.float32

In [383]:
y_train_tensor.dtype

torch.float32

In [384]:
model.parameters()

# Training Pipeline

In [385]:
#create model

model = MySimpleNN(X_train_tensor.shape[1])

#optimizer
optimizer = torch.optim.SGD( model.parameters(), lr = learning_rate )

#define loop

for epoch in range(epochs):

  for batch_feature, batch_labels in train_loader :
    #forward pass
    y_pred = model( batch_feature )

    #Loss calculate
    loss = loss_function(y_pred, batch_labels.reshape(-1,1))

    #zero gradient
    optimizer.zero_grad()

    #backward pass
    loss.backward()


    #parameter update
    optimizer.step()



  #print loss in each epoch

  print(f" {epoch+1} , Loss = {loss.item()} ")

 1 , Loss = 0.25420817732810974
 2 , Loss = 0.1408238708972931
 3 , Loss = 0.2349625676870346
 4 , Loss = 0.03326670825481415
 5 , Loss = 0.049791838973760605
 6 , Loss = 0.22626551985740662
 7 , Loss = 0.11371879279613495
 8 , Loss = 0.06492049992084503
 9 , Loss = 0.1528708040714264
 10 , Loss = 0.027909856289625168
 11 , Loss = 0.04281052201986313
 12 , Loss = 0.06740846484899521
 13 , Loss = 0.11632366478443146
 14 , Loss = 0.03158782795071602
 15 , Loss = 0.01108251791447401
 16 , Loss = 0.0025569754652678967
 17 , Loss = 0.01844208315014839
 18 , Loss = 0.07151591032743454
 19 , Loss = 0.06089689955115318
 20 , Loss = 0.10761244595050812
 21 , Loss = 0.0346684493124485
 22 , Loss = 0.056863632053136826
 23 , Loss = 0.030274122953414917
 24 , Loss = 0.00974288024008274
 25 , Loss = 0.0029493290930986404

# Training Pipeline Version 02

In [386]:
#create model

model = MySimpleNN(X_train_tensor.shape[1])

#optimizer
optimizer = torch.optim.SGD( model.parameters(), lr = learning_rate )

#define loop
batch_size = 32
epoch = 25
n_sample = len(X_train_tensor)

for epoch in range(epochs) :

  for start_idx in range( 0, n_sample, batch_size ) :
    end_idx = start_idx + batch_size

    print(f'Start Index : {start_idx}, & End Index : {end_idx}\n')

    X_batch = X_train_tensor[start_idx : end_idx]
    y_batch = y_train_tensor[start_idx : end_idx]

    # Forward pass

    y_pred = model( X_batch )
    loss = loss_function( y_pred, y_batch.reshape(-1, 1) )

    # Update step

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

  #print loss in each epoch

  # print(f" {epoch+1} , Loss = {loss.item()} ")

Start Index : 0, & End Index : 32

Start Index : 32, & End Index : 64

Start Index : 64, & End Index : 96

Start Index : 96, & End Index : 128

Start Index : 128, & End Index : 160

Start Index : 160, & End Index : 192

Start Index : 192, & End Index : 224

Start Index : 224, & End Index : 256

Start Index : 256, & End Index : 288

Start Index : 288, & End Index : 320

Start Index : 320, & End Index : 352

Start Index : 352, & End Index : 384

Start Index : 384, & End Index : 416

Start Index : 416, & End Index : 448

Start Index : 448, & End Index : 480

Start Index : 0, & End Index : 32

Start Index : 32, & End Index : 64

Start Index : 64, & End Index : 96

Start Index : 96, & End Index : 128

Start Index : 128, & End Index : 160

Start Index : 160, & End Index : 192

Start Index : 192, & End Index : 224

Start Index : 224, & End Index : 256

Start Index : 256, & End Index : 288

Start Index : 288, & End Index : 320

Start Index : 320, & End Index : 352

Start Index : 352, & End Index : 384

Start Index : 384, & End Index : 416

Start Index : 416, & End Index : 448

Start Index : 448, & End Index : 480

Start Index : 0, & End Index : 32

Start Index : 32, & End Index : 64

Start Index : 64, & End Index : 96

Start Index : 96, & End Index : 128

Start Index : 128, & End Index : 160

Start Index : 160, & End Index : 192

Start Index : 192, & End Index : 224

Start Index : 224, & End Index : 256

Start Index : 256, & End Index : 288

Start Index : 288, & End Index : 320

Start Index : 320, & End Index : 352

Start Index : 352, & End Index : 384

Start Index : 384, & End Index : 416

Start Index : 416, & End Index : 448

Start Index : 448, & End Index : 480

Start Index : 0, & End Index : 32

Start Index : 32, & End Index : 64

Start Index : 64, & End Index : 96

Start Index : 96, & End Index : 128

Start Index : 128, & End Index : 160

Start Index : 160, & End Index : 192

Start Index : 192, & End Index : 224

Start Index : 224, & End Index : 256

Start Index : 256, & End Index : 288

Start Index : 288, & End Index : 320

Start Index : 320, & End Index : 352

Start Index : 352, & End Index : 384

Start Index : 384, & End Index : 416

Start Index : 416, & End Index : 448

Start Index : 448, & End Index : 480

Start Index : 0, & End Index : 32

Start Index : 32, & End Index : 64

Start Index : 64, & End Index : 96

Start Index : 96, & End Index : 128

Start Index : 128, & End Index : 160

Start Index : 160, & End Index : 192

Start Index : 192, & End Index : 224

Start Index : 224, & End Index : 256

Start Index : 256, & End Index : 288

Start Index : 288, & End Index : 320

Start Index : 320, & End Index : 352

Start Index : 352, & End Index : 384

Start Index : 384, & End Index : 416

Start Index : 416, & End Index : 448

Start Index : 448, & End Index : 480

Start Index : 0, & End Index : 32

Start Index : 32, & End Index : 64

Start Index : 64, & End Index : 96

Start Index : 96, & End Index : 128

Start Index : 128, & End Index : 160

Start Index : 160, & End Index : 192

Start Index : 192, & End Index : 224

Start Index : 224, & End Index : 256

Start Index : 256, & End Index : 288

Start Index : 288, & End Index : 320

Start Index : 320, & End Index : 352

Start Index : 352, & End Index : 384

Start Index : 384, & End Index : 416

Start Index : 416, & End Index : 448

Start Index : 448, & End Index : 480

Start Index : 0, & End Index : 32

Start Index : 32, & End Index : 64

Start Index : 64, & End Index : 96

Start Index : 96, & End Index : 128

Start Index : 128, & End Index : 160

Start Index : 160, & End Index : 192

Start Index : 192, & End Index : 224

Start Index : 224, & End Index : 256

Start Index : 256, & End Index : 288

Start Index : 288, & End Index : 320

Start Index : 320, & End Index : 352

Start Index : 352, & End Index : 384

Start Index : 384, & End Index : 416

Start Index : 416, & End Index : 448

Start Index : 448, & End Index : 480

Start Index : 0, & End Index : 32

Start Index : 32, & End Index : 64

Start Index : 64, & End Index : 96

Start Index : 96, & End Index : 128

Start Index : 128, & End Index : 160

Start Index : 160, & End Index : 192

Start Index : 192, & End Index : 224

Start Index : 224, & End Index : 256

Start Index : 256, & End Index : 288

Start Index : 288, & End Index : 320

Start Index : 320, & End Index : 352

Start Index : 352, & End Index : 384

Start Index : 384, & End Index : 416

Start Index : 416, & End Index : 448

Start Index : 448, & End Index : 480

Start Index : 0, & End Index : 32

Start Index : 32, & End Index : 64

Start Index : 64, & End Index : 96

Start Index : 96, & End Index : 128

Start Index : 128, & End Index : 160

Start Index : 160, & End Index : 192

Start Index : 192, & End Index : 224

Start Index : 224, & End Index : 256

Start Index : 256, & End Index : 288

Start Index : 288, & End Index : 320

Start Index : 320, & End Index : 352

Start Index : 352, & End Index : 384

Start Index : 384, & End Index : 416

Start Index : 416, & End Index : 448

Start Index : 448, & End Index : 480

Start Index : 0, & End Index : 32

Start Index : 32, & End Index : 64

Start Index : 64, & End Index : 96

Start Index : 96, & End Index : 128

Start Index : 128, & End Index : 160

Start Index : 160, & End Index : 192

Start Index : 192, & End Index : 224

Start Index : 224, & End Index : 256

Start Index : 256, & End Index : 288

Start Index : 288, & End Index : 320

Start Index : 320, & End Index : 352

Start Index : 352, & End Index : 384

Start Index : 384, & End Index : 416

Start Index : 416, & End Index : 448

Start Index : 448, & End Index : 480

Start Index : 0, & End Index : 32

Start Index : 32, & End Index : 64

Start Index : 64, & End Index : 96

Start Index : 96, & End Index : 128

Start Index : 128, & End Index : 160

Start Index : 160, & End Index : 192

Start Index : 192, & End Index : 224

Start Index : 224, & End Index : 256

Start Index : 256, & End Index : 288

Start Index : 288, & End Index : 320

Start Index : 320, & End Index : 352

Start Index : 352, & End Index : 384

Start Index : 384, & End Index : 416

Start Index : 416, & End Index : 448

Start Index : 448, & End Index : 480

Start Index : 0, & End Index : 32

Start Index : 32, & End Index : 64

Start Index : 64, & End Index : 96

Start Index : 96, & End Index : 128

Start Index : 128, & End Index : 160

Start Index : 160, & End Index : 192

Start Index : 192, & End Index : 224

Start Index : 224, & End Index : 256

Start Index : 256, & End Index : 288

Start Index : 288, & End Index : 320

Start Index : 320, & End Index : 352

Start Index : 352, & End Index : 384

Start Index : 384, & End Index : 416

Start Index : 416, & End Index : 448

Start Index : 448, & End Index : 480

Start Index : 0, & End Index : 32

Start Index : 32, & End Index : 64

Start Index : 64, & End Index : 96

Start Index : 96, & End Index : 128

Start Index : 128, & End Index : 160

Start Index : 160, & End Index : 192

Start Index : 192, & End Index : 224

Start Index : 224, & End Index : 256

Start Index : 256, & End Index : 288

Start Index : 288, & End Index : 320

Start Index : 320, & End Index : 352

Start Index : 352, & End Index : 384

Start Index : 384, & End Index : 416

Start Index : 416, & End Index : 448

Start Index : 448, & End Index : 480

Start Index : 0, & End Index : 32

Start Index : 32, & End Index : 64

Start Index : 64, & End Index : 96

Start Index : 96, & End Index : 128

Start Index : 128, & End Index : 160

Start Index : 160, & End Index : 192

Start Index : 192, & End Index : 224

Start Index : 224, & End Index : 256

Start Index : 256, & End Index : 288

Start Index : 288, & End Index : 320

Start Index : 320, & End Index : 352

Start Index : 352, & End Index : 384

Start Index : 384, & End Index : 416

Start Index : 416, & End Index : 448

Start Index : 448, & End Index : 480

Start Index : 0, & End Index : 32

Start Index : 32, & End Index : 64

Start Index : 64, & End Index : 96

Start Index : 96, & End Index : 128

Start Index : 128, & End Index : 160

Start Index : 160, & End Index : 192

Start Index : 192, & End Index : 224

Start Index : 224, & End Index : 256

Start Index : 256, & End Index : 288

Start Index : 288, & End Index : 320

Start Index : 320, & End Index : 352

Start Index : 352, & End Index : 384

Start Index : 384, & End Index : 416

Start Index : 416, & End Index : 448

Start Index : 448, & End Index : 480

Start Index : 0, & End Index : 32

Start Index : 32, & End Index : 64

Start Index : 64, & End Index : 96

Start Index : 96, & End Index : 128

Start Index : 128, & End Index : 160

Start Index : 160, & End Index : 192

Start Index : 192, & End Index : 224

Start Index : 224, & End Index : 256

Start Index : 256, & End Index : 288

Start Index : 288, & End Index : 320

Start Index : 320, & End Index : 352

Start Index : 352, & End Index : 384

Start Index : 384, & End Index : 416

Start Index : 416, & End Index : 448

Start Index : 448, & End Index : 480

Start Index : 0, & End Index : 32

Start Index : 32, & End Index : 64

Start Index : 64, & End Index : 96

Start Index : 96, & End Index : 128

Start Index : 128, & End Index : 160

Start Index : 160, & End Index : 192

Start Index : 192, & End Index : 224

Start Index : 224, & End Index : 256

Start Index : 256, & End Index : 288

Start Index : 288, & End Index : 320

Start Index : 320, & End Index : 352

Start Index : 352, & End Index : 384

Start Index : 384, & End Index : 416

Start Index : 416, & End Index : 448

Start Index : 448, & End Index : 480

Start Index : 0, & End Index : 32

Start Index : 32, & End Index : 64

Start Index : 64, & End Index : 96

Start Index : 96, & End Index : 128

Start Index : 128, & End Index : 160

Start Index : 160, & End Index : 192

Start Index : 192, & End Index : 224

Start Index : 224, & End Index : 256

Start Index : 256, & End Index : 288

Start Index : 288, & End Index : 320

Start Index : 320, & End Index : 352

Start Index : 352, & End Index : 384

Start Index : 384, & End Index : 416

Start Index : 416, & End Index : 448

Start Index : 448, & End Index : 480

Start Index : 0, & End Index : 32

Start Index : 32, & End Index : 64

Start Index : 64, & End Index : 96

Start Index : 96, & End Index : 128

Start Index : 128, & End Index : 160

Start Index : 160, & End Index : 192

Start Index : 192, & End Index : 224

Start Index : 224, & End Index : 256

Start Index : 256, & End Index : 288

Start Index : 288, & End Index : 320

Start Index : 320, & End Index : 352

Start Index : 352, & End Index : 384

Start Index : 384, & End Index : 416

Start Index : 416, & End Index : 448

Start Index : 448, & End Index : 480

Start Index : 0, & End Index : 32

Start Index : 32, & End Index : 64

Start Index : 64, & End Index : 96

Start Index : 96, & End Index : 128

Start Index : 128, & End Index : 160

Start Index : 160, & End Index : 192

Start Index : 192, & End Index : 224

Start Index : 224, & End Index : 256

Start Index : 256, & End Index : 288

Start Index : 288, & End Index : 320

Start Index : 320, & End Index : 352

Start Index : 352, & End Index : 384

Start Index : 384, & End Index : 416

Start Index : 416, & End Index : 448

Start Index : 448, & End Index : 480

Start Index : 0, & End Index : 32

Start Index : 32, & End Index : 64

Start Index : 64, & End Index : 96

Start Index : 96, & End Index : 128

Start Index : 128, & End Index : 160

Start Index : 160, & End Index : 192

Start Index : 192, & End Index : 224

Start Index : 224, & End Index : 256

Start Index : 256, & End Index : 288

Start Index : 288, & End Index : 320

Start Index : 320, & End Index : 352

Start Index : 352, & End Index : 384

Start Index : 384, & End Index : 416

Start Index : 416, & End Index : 448

Start Index : 448, & End Index : 480

Start Index : 0, & End Index : 32

Start Index : 32, & End Index : 64

Start Index : 64, & End Index : 96

Start Index : 96, & End Index : 128

Start Index : 128, & End Index : 160

Start Index : 160, & End Index : 192

Start Index : 192, & End Index : 224

Start Index : 224, & End Index : 256

Start Index : 256, & End Index : 288

Start Index : 288, & End Index : 320

Start Index : 320, & End Index : 352

Start Index : 352, & End Index : 384

Start Index : 384, & End Index : 416

Start Index : 416, & End Index : 448

Start Index : 448, & End Index : 480

Start Index : 0, & End Index : 32

Start Index : 32, & End Index : 64

Start Index : 64, & End Index : 96

Start Index : 96, & End Index : 128

Start Index : 128, & End Index : 160

Start Index : 160, & End Index : 192

Start Index : 192, & End Index : 224

Start Index : 224, & End Index : 256

Start Index : 256, & End Index : 288

Start Index : 288, & End Index : 320

Start Index : 320, & End Index : 352

Start Index : 352, & End Index : 384

Start Index : 384, & End Index : 416

Start Index : 416, & End Index : 448

Start Index : 448, & End Index : 480

Start Index : 0, & End Index : 32

Start Index : 32, & End Index : 64

Start Index : 64, & End Index : 96

Start Index : 96, & End Index : 128

Start Index : 128, & End Index : 160

Start Index : 160, & End Index : 192

Start Index : 192, & End Index : 224

Start Index : 224, & End Index : 256

Start Index : 256, & End Index : 288

Start Index : 288, & End Index : 320

Start Index : 320, & End Index : 352

Start Index : 352, & End Index : 384

Start Index : 384, & End Index : 416

Start Index : 416, & End Index : 448

Start Index : 448, & End Index : 480

Start Index : 0, & End Index : 32

Start Index : 32, & End Index : 64

Start Index : 64, & End Index : 96

Start Index : 96, & End Index : 128

Start Index : 128, & End Index : 160

Start Index : 160, & End Index : 192

Start Index : 192, & End Index : 224

Start Index : 224, & End Index : 256

Start Index : 256, & End Index : 288

Start Index : 288, & End Index : 320

Start Index : 320, & End Index : 352

Start Index : 352, & End Index : 384

Start Index : 384, & End Index : 416

Start Index : 416, & End Index : 448

Start Index : 448, & End Index : 480

# Model Evaluation (Old)

In [387]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred= (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f" Accuracy = {accuracy.item()}")

 Accuracy = 0.5295475721359253

# Better Version

In [388]:
y_pred.shape

torch.Size([114, 1])

In [389]:
batch_labels.shape

torch.Size([7])

In [390]:
model.eval() # Evaluation mode

accuracy_list = []

with torch.no_grad():

  for batch_feature, batch_labels in test_loader :
    y_pred = model( batch_feature )
    y_pred = (y_pred > 0.8).float()

    # print(y_pred)

    batch_accuracy = ( y_pred.view(-1) == batch_labels ).float().mean().item()

    accuracy_list.append(batch_accuracy)


overall_accuracy = sum(accuracy_list) / len(accuracy_list)

print(overall_accuracy)

0.9644097238779068

In [391]:
accuracy_list

[1.0, 1.0, 0.96875, 0.8888888955116272]

# Summary

In [392]:
X_train_tensor.shape

torch.Size([455, 30])

In [393]:
!pip install torchinfo

Requirement already satisfied: torchinfo in /usr/local/lib/python3.13/dist-packages (1.8.0)

In [394]:
from torchinfo import summary

In [395]:
summary(model, input_size = (455,30))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
MySimpleNN                               [455, 1]                  --
├─Linear: 1-1                            [455, 1]                  31
├─Sigmoid: 1-2                           [455, 1]                  --
==========================================================================================
Total params: 31
Trainable params: 31
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.01
==========================================================================================
Input size (MB): 0.05
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.06
==========================================================================================