In [1]:
print("In the name of Allah")

In the name of Allah

# Perceptron

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import joblib

In [3]:
np.random.randn(3) * 1e-4

array([ 7.19258762e-05, -1.71989717e-04,  9.21038661e-05])

In [9]:
x = [3, 3, 3]
bias = -np.ones((len(x), 1))
bias

array([[-1.],
       [-1.],
       [-1.]])

In [36]:
class Perceptron :
  def __init__(self, eta, epochs) :
    self.weights = np.random.randn(3) * 1e-4
    print(f"Initial weights before training : \n{self.weights}")
    self.eta = eta
    self.epochs = epochs

  def activation_function(self, inputs, weights) :
    z = np.dot( inputs, weights )
    return np.where(z > 0, 1, 0)


  def fit( self, X, y ) :
    self.X = X
    self.y = y
    X_with_bias = np.c_[X, -np.ones((len(X), 1))]
    print(f"X with bias : \n{X_with_bias}")

    for epoch in range(self.epochs) :
      print(f"Epoch no : {epoch}")
      y_hat = self.activation_function(X_with_bias, self.weights)
      print(f"Predicted Value after forward pass : \n{y_hat}")

      error = y - y_hat
      print(f"Error : {error}")

      self.weights += self.eta * np.dot(X_with_bias.T, error)
      print(f"Updated Weight : \n{self.weights}")

  def predict( self, X ) :
    X_with_bias = np.c_[X, -np.ones((len(X), 1))]
    return self.activation_function(X_with_bias, self.weights)

# AND Operation

In [37]:
data = {
    'x1' : [0, 0, 1, 1],
    'x2' : [0, 1, 0, 1],
    'y'  : [0, 0, 0, 1]
}

AND = pd.DataFrame(data)

AND

   x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [38]:
X = AND.drop('y', axis = 1)
y = AND['y']
y

0    0
1    0
2    0
3    1
Name: y, dtype: int64

In [39]:
model = Perceptron(eta = 0.1, epochs = 10)

model.fit(X, y)

Initial weights before training :
[ 9.98308293e-05 -2.03848399e-05 -2.48262134e-04]
X with bias :
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Epoch no : 0
Predicted Value after forward pass :
[1 1 1 1]
Error : 0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
Updated Weight :
[-0.09990017 -0.10002038  0.29975174]
Epoch no : 1
Predicted Value after forward pass :
[0 0 0 0]
Error : 0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated Weight :
[ 9.98308293e-05 -2.03848399e-05  1.99751738e-01]
Epoch no : 2
Predicted Value after forward pass :
[0 0 0 0]
Error : 0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated Weight :
[0.10009983 0.09997962 0.09975174]
Epoch no : 3
Predicted Value after forward pass :
[0 1 1 1]
Error : 0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
Updated Weight :
[ 9.98308293e-05 -2.03848399e-05  2.99751738e-01]
Epoch no : 4
Predicted Value after forward pass :
[0 0 0 0]
Error : 0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated Weight :
[0.10009983 0.09997962 0.19975174]
Epoch no : 5
Predicted Value after forward pass :
[0 0 0 1]
Error : 0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weight :
[0.10009983 0.09997962 0.19975174]
Epoch no : 6
Predicted Value after forward pass :
[0 0 0 1]
Error : 0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weight :
[0.10009983 0.09997962 0.19975174]
Epoch no : 7
Predicted Value after forward pass :
[0 0 0 1]
Error : 0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weight :
[0.10009983 0.09997962 0.19975174]
Epoch no : 8
Predicted Value after forward pass :
[0 0 0 1]
Error : 0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weight :
[0.10009983 0.09997962 0.19975174]
Epoch no : 9
Predicted Value after forward pass :
[0 0 0 1]
Error : 0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weight :
[0.10009983 0.09997962 0.19975174]

In [40]:
model.predict(X)

array([0, 0, 0, 1])

In [41]:
model.weights

array([0.10009983, 0.09997962, 0.19975174])

# OR Gate

In [42]:
data = {
    'x1' : [0, 0, 1, 1],
    'x2' : [0, 1, 0, 1],
    'y'  : [0, 1, 1, 1]
}

OR = pd.DataFrame(data)
OR

   x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [43]:
X = OR.drop('y', axis = 1)
y = OR['y']

y

0    0
1    1
2    1
3    1
Name: y, dtype: int64

In [44]:
model_or = Perceptron(eta = 0.1, epochs = 10)

model_or.fit(X, y)

Initial weights before training :
[-1.94682410e-04  7.56397765e-05 -1.19629118e-04]
X with bias :
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Epoch no : 0
Predicted Value after forward pass :
[1 1 0 1]
Error : 0   -1
1    0
2    1
3    0
Name: y, dtype: int64
Updated Weight :
[ 9.98053176e-02  7.56397765e-05 -1.19629118e-04]
Epoch no : 1
Predicted Value after forward pass :
[1 1 1 1]
Error : 0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weight :
[9.98053176e-02 7.56397765e-05 9.98803709e-02]
Epoch no : 2
Predicted Value after forward pass :
[0 0 0 1]
Error : 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated Weight :
[ 0.19980532  0.10007564 -0.10011963]
Epoch no : 3
Predicted Value after forward pass :
[1 1 1 1]
Error : 0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weight :
[ 1.99805318e-01  1.00075640e-01 -1.19629118e-04]
Epoch no : 4
Predicted Value after forward pass :
[1 1 1 1]
Error : 0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weight :
[0.19980532 0.10007564 0.09988037]
Epoch no : 5
Predicted Value after forward pass :
[0 1 1 1]
Error : 0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weight :
[0.19980532 0.10007564 0.09988037]
Epoch no : 6
Predicted Value after forward pass :
[0 1 1 1]
Error : 0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weight :
[0.19980532 0.10007564 0.09988037]
Epoch no : 7
Predicted Value after forward pass :
[0 1 1 1]
Error : 0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weight :
[0.19980532 0.10007564 0.09988037]
Epoch no : 8
Predicted Value after forward pass :
[0 1 1 1]
Error : 0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weight :
[0.19980532 0.10007564 0.09988037]
Epoch no : 9
Predicted Value after forward pass :
[0 1 1 1]
Error : 0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weight :
[0.19980532 0.10007564 0.09988037]

In [47]:
model_or.predict(X)

array([0, 1, 1, 1])

In [49]:
model_or.weights

array([0.19980532, 0.10007564, 0.09988037])